### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by amicharski** [kazimkazam/todo-app#1] opened 2023-01-09 20:03 UTC
I recently created an account but when I login, I get this error in the console:
`Failed to load resource: the server responded with a status of 404 ()`

**Comment by kazimkazam** [comment] 2023-01-09 20:53
Hi @amicharski,

Thank you for the feedback.

Please try the following when you open the website:

- wait 10s-15s (should be more than enough). The server needs some time to wake up when it has not been used for some time;

- click Create New Account;

- insert the desired credentials. Please use hypothetical credentials, e.g., user@email.com;

- Click sign up;

- Then proceed to log in into your new account.

Let me know how it goes :)

**Comment by amicharski** [comment] 2023-01-09 20:56
I did it again just now and I still get an error

**Comment by kazimkazam** [comment] 2023-01-09 21:14
@amicharski 

Checking the database, I can see that your issue is related with the sign up part. The new user is not being created.

I think I know what the issue is... The issue is that no message is being shown to the user when he inserts an invalid password on sign up...

I thought I had this covered but apparently not... I will fix it.

But just to confirm that this is the issue now and not other,
Could you please try to use a password with at least 8 chars ? And it needs to have at least one number and one capital letter, for example, Pass1234

Thank you!

**Comment by kazimkazam** [comment] 2023-01-09 21:37
@amicharski

While I fix the issue ---> A error/message needs to let the user know that the sign up was unsuccessful because invalid credentials were inserted.

Please try with the following credentials or something like it:

username: test
email: test@email.com
password: Pass1234

email needs to have @email.com or @something.com
password needs to have at least one number and one capital letter, for example, Pass1234

**Comment by kazimkazam** [comment] 2023-01-10 00:41
Hi again @amicharski,

I believe the issue "A error/message needs to let the user know that the sign up was unsuccessful because invalid credentials were inserted" is now fixed.

Above I mentioned that I thought the issue was covered, and I thought right. But, in the meantime, something changed...

The issue was related with createAsyncThunk which was being fulfilled even when fetch had status.code 400 / 404. This is now fixed.

Something changed how createAsyncThunk processes fetch responses or something... Which lead to this issue. 

To solve the issue, fetches now only return a response to createAsyncThunk if response.ok otherwise they throw an error and send status.code as message which you can check, e.g., on google devTools with redux devTools.

I used this opportunity to also implement more warnings on sign up and login, e.g., it now checks on the client side if the user inserted an email that is a valid email and a password that checks some rules, if not a warning will appear.

I would like to thank you again for the feedback. This allowed me to improve the website.

So, at the moment, you should be able to use the todo-app without any problems.

----------------------------------------------------------------------------------------------
Please try with the following credentials or something like it:

username: test
email: test@email.com
password: Pass1234

- email needs to have @email.com or @something.com as the example above
- password needs to have at least one number and one capital letter, as the example above
-----------------------------------------------------------------------------------------------

If you try to create an account with already used credentials or login with wrong credentials, a warning will appear "Ooops... Wrong email and/or password! Please try again." above the sign up or login div, and a status code 404 will appear on redux devTools sign up / login state.


Please let me know if you are now able to create an account, login and use the website.

Thank you :)

**Closed** 2023-01-12 16:07 UTC
